# See https://redoc.ly/docs/cli/configuration/ for more information.
apis:
  sample@1.0: 
    root: openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: error
features.openapi:
  showConsole: true
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"
  generateCodeSamples:
    languages:  # Array of language config objects; indicates in which languages to generate code samples.
      - lang: curl
      - lang: Node.js
      - lang: JavaScript
      - lang: PHP
      - lang: Python
